// Generated by CoffeeScript 1.6.2
(function() {
  window.SWMap = (function() {
    function SWMap() {}

    return SWMap;

  })();

  window.SWEvent = (function() {
    function SWEvent() {}

    SWEvent.all = function() {
      return $.get("/datasets/events.json", function(events) {
        var event, _i, _len, _results;

        events = _.sortBy(events, function(event) {
          return new Date(event['start_date']);
        });
        _results = [];
        for (_i = 0, _len = events.length; _i < _len; _i++) {
          event = events[_i];
          _results.push(console.log(event['start_date']));
        }
        return _results;
      }, "json");
    };

    return SWEvent;

  })();

  $(function() {
    return SWEvent.all();
  });

}).call(this);
