// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.SWMap = (function() {
    function SWMap() {
      this.addEvents = __bind(this.addEvents, this);
    }

    SWMap.prototype.map = null;

    SWMap.prototype.mapOptions = {
      center: new google.maps.LatLng(-34.397, 150.644),
      zoom: 8,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };

    SWMap.prototype.draw = function() {
      return this.map = new google.maps.Map(document.getElementById("map-canvas"), this.mapOptions);
    };

    SWMap.prototype.addEvents = function(events) {
      var event, pos, _i, _len, _results;

      _results = [];
      for (_i = 0, _len = events.length; _i < _len; _i++) {
        event = events[_i];
        pos = new google.maps.LatLng(event.location['lat'], event.location['lng']);
        _results.push(new google.maps.Marker({
          position: pos,
          map: this.map,
          title: event.city
        }));
      }
      return _results;
    };

    return SWMap;

  })();

  window.SWEvent = (function() {
    SWEvent.all = function(cb) {
      return $.get("/datasets/events.json", function(events) {
        var allEvents, event, _i, _len;

        events = _.sortBy(events, function(event) {
          return new Date(event['start_date']);
        });
        allEvents = [];
        for (_i = 0, _len = events.length; _i < _len; _i++) {
          event = events[_i];
          allEvents.push(new SWEvent(event));
        }
        return cb(allEvents);
      }, "json");
    };

    function SWEvent(attributes) {
      this.id = attributes['id'];
      this.city = attributes['city'];
      this.location = attributes['location'];
    }

    return SWEvent;

  })();

  $(function() {
    var map;

    map = new SWMap();
    map.draw();
    return SWEvent.all(function(events) {
      return map.addEvents(events);
    });
  });

}).call(this);
